services:
  # 1. Django Web Service
  - type: web
    name: server
    runtime: python
    buildCommand: |
      cd server && pip install -r requirements.txt
    startCommand: |
      cd server && python manage.py migrate && gunicorn server.wsgi:application --log-file - --log-level debug

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: prod_db
          property: connectionString
      - key: SECRET_KEY 
        generateValue: true
      - key: REDIS_URL
        fromService:
          name: redis-prod
          type: redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          name: redis-prod
          type: redis
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: server.settings.prod

  # 2. Celery Worker
  - type: worker
    name: celery-worker
    runtime: python
    buildCommand: |
      cd server && pip install -r requirements.txt
    startCommand: |
      cd server && celery -A server worker --loglevel=info
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: redis-prod
          type: redis
          property: internalconnectionString

  # 3. Celery Beat (Scheduler)
  - type: worker
    name: celery-beat
    runtime: python
    buildCommand: | 
      cd server && pip install -r requirements.txt
    startCommand: |
      cd server && celery -A server beat --loglevel=info 
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: redis-prod
          type: redis
          property: connectionString

  # 4. Redis (Celery Broker)
  - type: redis
    name: redis-prod
    plan: free 
    ipAllowList: [] 

  # 5. PostgreSQL Database
databases:
  - name: prod_db 
    postgresMajorVersion: '16'
    region: frankfurt 
    plan: free 
    databaseName: prod_db 
    user: root_user 
    ipAllowList: [] 
      

    