# Use official Python image as base
FROM python:3.13-slim

WORKDIR /server

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /server/

RUN  pip install -r requirements.txt

COPY . /server/

EXPOSE 5000

CMD ["python", "manage.py", "runserver", "0.0.0.0:5000"]
