# Generated by Django 5.1.6 on 2025-03-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_farmer_user_alter_farm_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='phone',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
