# Generated by Django 5.1.6 on 2025-03-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_user_farm_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='farm_uuid',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
