# Generated by Django 5.1.6 on 2025-04-01 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_sensordata_farm_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='max_ideal_nitrogen',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='max_ideal_phosphorous',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='max_ideal_potassium',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='min_ideal_nitrogen',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='min_ideal_phosphorous',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='min_ideal_potassium',
        ),
    ]
