# Generated by Django 5.1.6 on 2025-04-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_crop_max_ideal_nitrogen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='humidity_max',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='humidity_min',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='nitrogen_max_ppm',
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='nitrogen_min_ppm',
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='phosphorous_max_ppm',
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='phosphorous_min_ppm',
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='potassium_max_ppm',
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='potassium_min_ppm',
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
    ]
