# Generated by Django 5.1.6 on 2025-04-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_crop_humidity_max_crop_humidity_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('M', 'Maintenance')], default='A', max_length=1),
        ),
    ]
