# Generated by Django 5.1.6 on 2025-04-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
