# Generated by Django 4.2.20 on 2025-05-09 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_notification_recommendation'),
    ]

    operations = [
    ]
