# Generated by Django 4.2.20 on 2025-05-09 18:02

from django.db import migrations, models
import random

def generate_unique_farm_uuid():
    return str(random.randint(100000, 999999))

def populate_farm_uuids(apps, schema_editor):
    Farm = apps.get_model('app', 'Farm')
    for farm in Farm.objects.all():
        while True:
            uuid = generate_unique_farm_uuid()
            if not Farm.objects.filter(farm_uuid=uuid).exists():
                farm.farm_uuid = uuid
                farm.save()
                break

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20250509_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farm_uuid',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),

    migrations.RunPython(populate_farm_uuids),

         migrations.AlterField(
            model_name='farm',
            name='farm_uuid',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]

