# Generated by Django 4.2.20 on 2025-05-09 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_farm_farm_uuid'),
    ]

    operations = [
    ]
